module.exports = {
    Audio: require('./Audio'),
    Author: require('./Author'),
    Category: require('./Category'),
    Collaboration: require('./Collaboration'),
    Data: require('./Data'),
    EditorChoice: require('./EditorChoice'),
    Gallery: require('./Gallery'),
    Image: require('./Image'),
    Quote: require('./Quote'),
    Post: require('./Post'),
    Project: require('./Project'),
    Tag: require('./Tag'),
    User: require('./User'),
    Video: require('./Video'),
    EditLog: require('./EditLog'),
}
