module.exports = {
    Post: require('./Post'),
    EditorChoice: require('./EditorChoice'),
    Image: require('./Image'),
    Video: require('./Video'),
    Audio: require('./Audio'),
    Event: require('./Event'),
    Topic: require('./Topic'),
    Category: require('./Category'),
    Tag: require('./Tag'),
    Contact: require('./Contact'),
    User: require('./User'),
    Partner: require('./Partner'),
    External: require('./External'),
}
