module.exports = {
    Post: require('./Post'),
    EditorChoice: require('./EditorChoice'),
    Image: require('./Image'),
    Video: require('./Video'),
    Audio: require('./Audio'),
    Event: require('./Event'),
    Topic: require('./Topic'),
    Category: require('./Category'),
    Tag: require('./Tag'),
    Contact: require('./Contact'),
    User: require('./User'),
    Partner: require('./Partner'),
    External: require('./External'),
    Show: require('./Show'),
    VideoEditorChoice: require('./VideoEditorChoice'),
    EditLog: require('./EditLog'),
    PromotionVideo: require('./PromotionVideo'),
    ArtShow: require('./ArtShow'),
    Section: require('./Section'),
    Serie: require('./Serie'),
    Sale: require('./Sale'),
    Sponsor: require('./Sponsor'),
}
