module.exports = {
    Post: require('./Post'),
    EditorChoice: require('./EditorChoice'),
    Image: require('./Image'),
    Video: require('./Video'),
    Audio: require('./Audio'),
    Event: require('./Event'),
    Topic: require('./Topic'),
    Section: require('./Section'),
    Category: require('./Category'),
    Tag: require('./Tag'),
    Contact: require('./Contact'),
    User: require('./User'),
    Company: require('./Company'),
    Partner: require('./Partner'),
    External: require('./External'),
    Watch: require('./Watch'),
    WatchBrand: require('./WatchBrand'),
    WatchStore: require('./WatchStore'),
    WatchFunction: require('./WatchFunction'),
}
