ALTER TABLE "Audio" ADD COLUMN title text;
ALTER TABLE "EditLog" ADD COLUMN "summary" TEXT;
ALTER TABLE "EditLog" ADD COLUMN "brief" TEXT;
ALTER TABLE "EditLog" ADD COLUMN "content" TEXT;
ALTER TABLE "Post" ADD COLUMN "summaryHtml" text;
ALTER TABLE "Post" ADD COLUMN "summaryApiData" text;
ALTER TABLE "Post" ADD COLUMN "briefHtml" text;
ALTER TABLE "Post" ADD COLUMN "briefApiData" text;
ALTER TABLE "Post" ADD COLUMN "contentHtml" text;
ALTER TABLE "Post" ADD COLUMN "contentApiData" text;
ALTER TABLE "Video" RENAME COLUMN "title" TO "name";
