-- drop unwanted NOT NULL for columns in "Post"
ALTER TABLE "Post" ALTER COLUMN subtitle DROP NOT NULL;
ALTER TABLE "Post" ALTER COLUMN "ogDescription" DROP NOT NULL;
ALTER TABLE "Post" ALTER COLUMN "ogTitle" DROP NOT NULL;
ALTER TABLE "Post" ALTER COLUMN otherbyline DROP NOT NULL;
